routes/web.php
<?php

use App\Http\Requests\UserSearchRequest;
use App\Http\Requests\UserStoreRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('main');


Route::resource('/users', UserController::class);
//
//Route::get('/users', [UserController::class, 'index'])->name('users');
//
//Route::get('/users/create', [UserController::class, 'create'])->name('users.create');
//
//Route::post('/users', [UserController::class, 'store'])->name('users.store');
//
Route::get('/users/{user}/edit', [UserController::class, 'show'])->name('users.show');

//Route::put('/users/{user}', [UserController::class, 'edit'])->name('users.edit');
//
Route::get('/users/{user}', [UserController::class, 'view'])->name('user.view');

//Route::delete('/users/{user}', [UserController::class, 'destroy'] )->name('users.delete');

Route::post('/users', [UserController::class, 'restore'])->name('users.restore');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserSearchRequest;
use App\Http\Requests\UserStoreRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Models\User;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    public function index(UserSearchRequest $request)
    {
        $query = User::query();

        switch ($request->get('activity')) {
            case 'all':
                $query->withTrashed();
                break;
            case 'inactive':
                $query->onlyTrashed();
        }

        $name = $request->get('name');
        if ($name) {
            $query->whereName($name);
        }

        $query->where('email', 'like','%' . $request->get('email'));

        return view('users.index', [
            'users' => $query->get(),
            'mailDomains' => DB::table('users')
                ->selectRaw("distinct right(email, length(email)-INSTR(email, '@')) as mail_domain")
                ->get()
                ->pluck('mail_domain'),
        ]);
    }

    public function create()
    {
        return view('users.create');
    }

    public function store(UserStoreRequest $request)
    {
        $user = new User();
        $user->fill($request->validated());
        $user->save();
        return redirect(\route('users.index'));
    }

    public function show(User $user)
    {
        return view('users.edit', ['user' => $user]);
    }

    public function edit(User $user, UserUpdateRequest $request)
    {
        $user->update($request->validated());
        return redirect(\route('users.index'));
    }

    public function destroy(User $user)
    {
        $user->delete();
        return redirect(\route('users.index'));
    }

    public function restore(User $user)
    {
        User::query()
            ->restore($user->id);
        return redirect(\route('users.index'));
    }

    public function view(User $user)
    {
        return view('users.view', ['user' => $user]);
    }
}

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    @include('layouts.partials.head')
</head>
<body>
@include('layouts.partials.nav')
@include('layouts.partials.header')
<div class="container">
    @if($errors->any())
        <div class="alert alert-danger" role="alert">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
    @endif

    @yield('content')

</div>
@include('layouts.partials.footer')
@include('layouts.partials.footer-scripts')
 </body>
</html>

resources/views/layouts/partials/footer-scripts.blade.php
<!-- Bootstrap core JavaScript
================================================= -->
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>


<script>
    window.document.addEventListener("DOMContentLoaded", function () {
        let button = document.querySelector('#passwordHide');
        button.addEventListener('click', function () {
            let input = document.querySelector("[name='password']");
            let type = input.getAttribute('type');
            if (type === 'password') {
                type = 'text';
                this.innerText = 'Hide';
            } else {
                type = 'password';
                this.innerText = 'Show';
            }
            input.setAttribute('type', type);
        });
    });
</script>

resources/views/layouts/partials/footer.blade.php
<footer class="text-muted">

</footer>

resources/views/layouts/partials/head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<title>Album example for Bootstrap</title>
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

resources/views/layouts/partials/header.blade.php
<section class="jumbotron text-center">
</section>

resources/views/layouts/partials/nav.blade.php
<div class="collapse bg-inverse" id="navbarHeader">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 py-4">
                <h4 class="text-white">About</h4>
                <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
            </div>
            <div class="col-sm-4 py-4">
                <h4 class="text-white">Contact</h4>
                <ul class="list-unstyled">
                    <li><a href="#" class="text-white">Follow on Twitter</a></li>
                    <li><a href="#" class="text-white">Like on Facebook</a></li>
                    <li><a href="#" class="text-white">Email me</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="navbar navbar-inverse bg-inverse">
    <div class="container d-flex justify-content-betIen">
        <a href="{{route('users.index')}}" class="navbar-brand">Users</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</div>

resources/views/users/create.blade.php
@extends('layouts.main')
@section('content')
    <form method="POST" action="{{route('users.store')}}">
        @csrf
        <div class="mb-3">
            <label for="exampleInputName" class="form-label">Имя пользователя</label>
            <input name="name" type="text" class="form-control" id="exampleInputName"  value="{{ old('name') }}">
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Электронная почта</label>
            <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"  value="{{ old('email') }}">
        </div>

        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Пароль</label>
            <div class="input-group mb-3">
                <input  name="password" type="password"  class="form-control" value="{{ old('password') }}" id="exampleInputPassword1" required aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" id="passwordHide" type="button">Show</button>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Создать пользователя</button>
    </form>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.main')
@section('content')
    <form method="POST" action="{{route('users.edit', $user->id)}}">
        @csrf
        @method('PUT')
        <div class="mb-3">
            <label for="exampleInputName" class="form-label">Имя пользователя</label>
            <input name="name" type="text" class="form-control" id="exampleInputName" value="{{ old('name', $user->name) }}" required>
            <span class="help-text"></span>
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Электронная почта</label>
            <input name="email" type="email" class="form-control" value="{{ old('email', $user->email) }}" id="exampleInputEmail1" aria-describedby="emailHelp" required>
        </div>

        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Пароль</label>
            <div class="input-group mb-3">
                <input  name="password" type="password"  class="form-control"value="{{ old('password',$user->password) }}" id="exampleInputPassword1" required aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" id="passwordHide" type="button">Show</button>
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Изменить пользователя</button>
    </form>

@endsection

resources/views/users/index.blade.php
@extends('layouts.main')
@section('content')
    <div class="input-group mb-3">
        <a href="{{route('users.create')}}" class="btn btn-success">Создать пользователя</a>
    </div>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <form role="form" action="{{route('users.index')}}">
            <input type="text" class="form-control" name="name" placeholder="Поиск... "
                   value="{{old('name')}}" aria-label="Text input with dropdown button">
            <select name="email">
                <option value="">Email</option>
                @foreach($mailDomains as $mailDomain)
                    <option value="{{$mailDomain}}">{{$mailDomain}}</option>
                @endforeach
            </select>
            <select name="activity">
                <option value="all">Все</option>
                <option value="active" selected>Активный</option>
                <option value="inactive">Удаленный</option>
            </select>
            <button type="submit">Поиск</button>
        </form>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Updated at</th>
            <th scope="col">Created at</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr>
                <th scope="row"><a href="{{route('user.view', $user)}}">{{$user->id}}</a></th>
                <td>{{$user->name}}</td>
                <td>{{$user->email}}</td>
                <td>{{$user->updated_at}}</td>
                <td>{{$user->created_at}}</td>
                <td>
                    @if($user->trashed())
                        <form method="POST" action="{{route('users.restore', $user)}}">
                            <button class="btn btn-outline-primary btn-xs btn-block">Восстановить</button>
                            @csrf
                        </form>
                        @else
                    <form action="{{route('users.show', $user)}}">
                        <button class="btn btn-outline-warning btn-xs btn-block">Изменить</button>
                    </form>
                    <br/>
                    <form action="{{route('users.destroy', $user)}}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-outline-danger btn-xs btn-block">Удалить</button>
                    </form>
                    @endif
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection

resources/views/users/view.blade.php
@extends('layouts.main')
@section('content')

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Updated at</th>
            <th scope="col">Created at</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">{{$user->id}}</th>
                <td>{{$user->name}}</td>
                <td>{{$user->email}}</td>
                <td>{{$user->updated_at}}</td>
                <td>{{$user->created_at}}</td>
                <td>
                    @if($user->trached())
                        <form action="{{route('users.restore', $user)}}">
                            <button class="btn btn-outline-primary btn-xs btn-block">Восстановить</button>
                        </form>
                    @endif
                    <form action="{{route('users.show', $user)}}">
                        <button class="btn btn-outline-warning btn-xs btn-block">Изменить</button>
                    </form>
                    <br/>
                    <form action="{{route('users.destroy', $user)}}" method="POST" >
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-outline-danger btn-xs btn-block">Удалить</button>
                    </form>
                </td>
            </tr>
        </tbody>
    </table>
@endsection